### ISSUE TITLE
Repository not deployed - can't grade!

### ISSUE THREAD

**Issue by sandblasta** [jhlateef/week7responsive#2]
You need to deploy the repository to GitHub Pages in order for me to be able to view it.

**Comment by jhlateef** [comment]
Prof. Lloyd, are you not receiving my emails? I've sent two already. Please
reply when you get a chance. thanks. ~ Jamil

**Comment by sandblasta** [comment]
Hi Jamil, 

I haven't gotten a single one of your emails! I wonder if your email account is experiencing the same issue that mine has been. In any case, would you re-send them so that I can have a look?

**Comment by jhlateef** [comment]
This was the email:

“Prof. Lloyd,

Good evening. This is Jamil. I just got your email about there being an
issue receiving emails or something. So, I'm sending this to you from my
personal account.

I went back on to github and re-uploaded the files as you requested. So
that's good. Now, I'm just having trouble actually deploying it. Seems to
be a bit confusing. Can you help me with this?

I tried to work on week 8, but I'm unable to access the class One Drive. I
did get your message on openlab with the alternate link. But the
instructions on how to complete the assignment are still on the one drive I
believe. So, I'm kind of in a rough spot with that one.

In the previous email I sent you which I'm assuming you didn't receive, I
talked about how I'm really scrambling to get these last assignments in and
it's as stressful as you can expect. I only have a few more assignments to
go so I was wondering if you would be against me taking an incomplete? This
would truly solve all my Problems with this course. And I can actually turn
in a quality Project 1, and Final Project.

What do you think?

Best,
Jamil”

**Comment by sandblasta** [comment]
I did see that email. 

I just forwarded to you the email that i sent in reply. just in case. 

Of course, that has passed, and I am happy to give you the INC. 

Did you receive the IRP form that I prepared for you?

**Comment by jhlateef** [comment]
Thank very much. That solves everything. The anxiety is over. I can’t thank
you enough 🙏🏾

No, I have not received the form. Please email to my personal. CUNY email
has been crazy ***@***.***)
